import type { Project, Task, Resource, TeamMember } from "./project-types"

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 1,
    name: "Rediseño del Sitio Web",
    description: "Renovación completa del sitio web de la empresa con diseño moderno",
    start_date: "2025-01-15",
    end_date: "2025-04-30",
    total_budget: 50000,
    manager_id: 5,
    status: "active", // Added status field
  },
  {
    id: 2,
    name: "Desarrollo de App Móvil",
    description: "Aplicación nativa iOS y Android para interacción con clientes",
    start_date: "2025-02-01",
    end_date: "2025-07-15",
    total_budget: 120000,
    manager_id: 5,
    status: "active", // Added status field
  },
  {
    id: 3,
    name: "Campaña de Marketing Q2",
    description: "Campaña de marketing digital para lanzamiento de producto",
    start_date: "2025-04-01",
    end_date: "2025-06-30",
    total_budget: 35000,
    manager_id: 1,
    status: "planning", // Added status field
  },
  {
    id: 4,
    name: "Actualización de Infraestructura",
    description: "Migración de servidores y configuración de infraestructura en la nube",
    start_date: "2025-03-01",
    end_date: "2025-05-31",
    total_budget: 75000,
    manager_id: 3,
    status: "completed", // Added status field
  },
]

export const INITIAL_TASKS: Task[] = [
  {
    id: 1,
    project_id: 1,
    title: "Diseño UI/UX",
    description: "Crear wireframes y mockups",
    assignee: "Sarah Chen",
    start_date: "2025-01-15",
    due_date: "2025-02-15",
    status: "completed",
    progress: 100,
    estimated_hours: 120,
    budget_allocated: 8000,
  },
  {
    id: 2,
    project_id: 1,
    title: "Desarrollo Frontend",
    description: "Implementar diseño responsive",
    assignee: "Mike Johnson",
    start_date: "2025-02-16",
    due_date: "2025-03-30",
    status: "in_progress",
    progress: 65,
    estimated_hours: 200,
    budget_allocated: 15000,
  },
  {
    id: 3,
    project_id: 1,
    title: "Integración Backend",
    description: "Desarrollo de API y configuración de base de datos",
    assignee: "Alex Kumar",
    start_date: "2025-03-01",
    due_date: "2025-04-15",
    status: "in_progress",
    progress: 40,
    estimated_hours: 150,
    budget_allocated: 12000,
  },
  {
    id: 4,
    project_id: 1,
    title: "Pruebas y QA",
    description: "Pruebas exhaustivas en todos los dispositivos",
    assignee: "Emily Rodríguez",
    start_date: "2025-04-01",
    due_date: "2025-04-25",
    status: "not_started",
    progress: 0,
    estimated_hours: 80,
    budget_allocated: 5000,
  },
  {
    id: 5,
    project_id: 2,
    title: "Desarrollo iOS",
    description: "Construir aplicación nativa iOS",
    assignee: "Mike Johnson",
    start_date: "2025-02-01",
    due_date: "2025-05-30",
    status: "in_progress",
    progress: 55,
    estimated_hours: 400,
    budget_allocated: 45000,
  },
  {
    id: 6,
    project_id: 2,
    title: "Desarrollo Android",
    description: "Construir aplicación nativa Android",
    assignee: "Alex Kumar",
    start_date: "2025-02-01",
    due_date: "2025-05-30",
    status: "in_progress",
    progress: 50,
    estimated_hours: 400,
    budget_allocated: 45000,
  },
  {
    id: 7,
    project_id: 2,
    title: "Backend API",
    description: "API RESTful para aplicaciones móviles",
    assignee: "Sarah Chen",
    start_date: "2025-02-15",
    due_date: "2025-04-30",
    status: "completed",
    progress: 100,
    estimated_hours: 250,
    budget_allocated: 20000,
  },
  {
    id: 8,
    project_id: 2,
    title: "Despliegue en Tiendas",
    description: "Enviar a App Store y Play Store",
    assignee: "Emily Rodríguez",
    start_date: "2025-06-01",
    due_date: "2025-07-15",
    status: "not_started",
    progress: 0,
    estimated_hours: 60,
    budget_allocated: 5000,
  },
  {
    id: 9,
    project_id: 3,
    title: "Creación de Contenido",
    description: "Posts de blog, videos y gráficos",
    assignee: "Emily Rodríguez",
    start_date: "2025-04-01",
    due_date: "2025-05-15",
    status: "in_progress",
    progress: 30,
    estimated_hours: 100,
    budget_allocated: 10000,
  },
  {
    id: 10,
    project_id: 3,
    title: "Campaña en Redes Sociales",
    description: "Estrategia multiplataforma en redes sociales",
    assignee: "Sarah Chen",
    start_date: "2025-04-15",
    due_date: "2025-06-30",
    status: "not_started",
    progress: 0,
    estimated_hours: 120,
    budget_allocated: 15000,
  },
  {
    id: 11,
    project_id: 4,
    title: "Migración a la Nube",
    description: "Mover servidores a infraestructura AWS",
    assignee: "Alex Kumar",
    start_date: "2025-03-01",
    due_date: "2025-04-30",
    status: "completed",
    progress: 100,
    estimated_hours: 200,
    budget_allocated: 40000,
  },
  {
    id: 12,
    project_id: 4,
    title: "Auditoría de Seguridad",
    description: "Revisión exhaustiva de seguridad",
    assignee: "Mike Johnson",
    start_date: "2025-04-15",
    due_date: "2025-05-31",
    status: "blocked",
    progress: 20,
    estimated_hours: 100,
    budget_allocated: 20000,
  },
]

export const INITIAL_RESOURCES: Resource[] = [
  { id: 1, name: "Sarah Chen", type: "Humano", hourly_rate: 85, availability_hours: 160 },
  { id: 2, name: "Mike Johnson", type: "Humano", hourly_rate: 90, availability_hours: 160 },
  { id: 3, name: "Alex Kumar", type: "Humano", hourly_rate: 80, availability_hours: 160 },
  { id: 4, name: "Emily Rodríguez", type: "Humano", hourly_rate: 75, availability_hours: 160 },
  { id: 5, name: "Servidores de Desarrollo", type: "Material", hourly_rate: 25, availability_hours: 720 },
  { id: 6, name: "Licencias de Software de Diseño", type: "Material", hourly_rate: 15, availability_hours: 500 },
]

export const INITIAL_TEAM: TeamMember[] = [
  { id: 1, name: "Sarah Chen", role: "Desarrolladora Senior", email: "sarah.chen@empresa.com" },
  { id: 2, name: "Mike Johnson", role: "Desarrollador Full Stack", email: "mike.johnson@empresa.com" },
  { id: 3, name: "Alex Kumar", role: "Desarrollador Backend", email: "alex.kumar@empresa.com" },
  { id: 4, name: "Emily Rodríguez", role: "Ingeniera QA", email: "emily.rodriguez@empresa.com" },
  { id: 5, name: "David Park", role: "Gerente de Proyecto", email: "david.park@empresa.com" },
]
